
set -g default-command /bin/zsh

# 重载tmux配置文件
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

set -g base-index 1                       # 设置窗口的起始下标为1
set -g pane-base-index 1                  # 设置面板的起始下标为1
set-option -g mouse on                    # 支持鼠标
set -g renumber-windows on                # 关掉某个窗口后，编号重排
set -g set-clipboard on                   # 剪贴板
set -g default-terminal "screen-256color" # 设置默认终端模式为 256color


# window 分屏
unbind '"'
bind - splitw -v -c "#{pane_current_path}"

unbind %
bind = splitw -h -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 绑定Ctrl+hjkl键为面板上下左右调整边缘的快捷指令
bind -r ^k resizep -U 10 # 绑定Ctrl+k为往↑调整面板边缘10个单元格
bind -r ^j resizep -D 10 # 绑定Ctrl+j为往↓调整面板边缘10个单元格
bind -r ^h resizep -L 10 # 绑定Ctrl+h为往←调整面板边缘10个单元格
bind -r ^l resizep -R 10 # 绑定Ctrl+l为往→调整面板边缘10个单元格


# 启用窗口自动重命名
set-option -g automatic-rename on
# 设置自动重命名格式为当前文件夹的基名
set-option -g automatic-rename-format "#{b:pane_current_path}"
# 自定义新建窗口
bind n new-window -c "#{pane_current_path}"
# 自定义关闭窗口（禁止提示）
bind-key C-q kill-window
# 自定义新建窗口路径
bind c new-window -c "$HOME"



setenv -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins'


# 插件管理器
# ==================== 插件管理 (TPM) ====================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# 插件

# ==================== tmux-resurrect 配置 ====================
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'ssh "~ssh *" mysql psql python python3 ipython "~vault *"'
set -g @resurrect-save-bash-history 'on'

# 自定义保存目录（可选）
set -g @resurrect-dir '~/.tmux/resurrect'

# ==================== 快捷键绑定 ====================
# 保存和恢复快捷键
bind-key S run-shell '~/.tmux/plugins/tmux-resurrect/scripts/save.sh'
bind-key R run-shell '~/.tmux/plugins/tmux-resurrect/scripts/restore.sh'



# ==================== tmux-continuum 配置 ====================
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'fullscreen'
set -g @continuum-save-interval '15'


# set -g @plugin 'tmux-plugins/tmux-yank'
# 显示prefix键有没有被按下
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_status_modules_right "application session user host date_time"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"
























run '~/.tmux/plugins/tpm/tpm'

